### ISSUE TITLE
Build for OSX

### ISSUE THREAD

**Issue by gizmomogwai** [trikko/guino#1]
Nice project!!!
I had to add 
```
lflags "-L$HOME/lib" platform="osx"
```
and copy the generated dylib to `~/lib` (which is the local std folder on osx for dylibs) to get the example working.

Is it also possible to get windows that are resizable in osx?

**Comment by trikko** [comment]
Thank you!

The following instruction, reported on main page, should work fine. Did you try it?
Anyway any custom directory works :)

```sudo cp guino/webview/build/library/libwebview.* /usr/local/lib/```

Adding a hint to ```webview.size(800, 600, XXX)``` should make the windows resizable. Does it work?

Available [hints](https://github.com/trikko/guino/blob/d69957fec986d25d6d76a91a11159e90e0dc2eb5/source/guino/package.d#L8C6-L8C23)

**Comment by trikko** [comment]
Maybe you have to call ```sudo ldconfig``` to recreate the link cache. Not sure it works on macOS as well, but it should.

**Comment by gizmomogwai** [comment]
Not so sure about the directories... I think the problem is, that you need to link at compile time and at runtime against the dylib. After reading some man pages, I think `~/lib` is _not_ one of the folders that are by default looked at for dylibs in osx (whereas your mentioned folders are part of the lookup strategy). One can adjust that with `DYLD_LIBRARY_PATH` but thats something else.

**Comment by gizmomogwai** [comment]
> Thank you!
> 
> The following instruction, reported on main page, should work fine. Did you try it? Anyway any custom directory works :)
> 
> `sudo cp guino/webview/build/library/libwebview.* /usr/local/lib/`
> 
> Adding a hint to `webview.size(800, 600, XXX)` should make the windows resizable. Does it work?
> 
> Available [hints](https://github.com/trikko/guino/blob/d69957fec986d25d6d76a91a11159e90e0dc2eb5/source/guino/package.d#L8C6-L8C23)

`WEBVIEW_HINT_NONE` works for me, thanks a lot!
I do have problems with `WEBVIEW_HINT_MIN` and `WEBVIEW_HINT_MAX` because I cannot the the minimal example window anymore, but `WEBVIEW_HINT_FIXED` works again as expected.

Thanks!

**Comment by trikko** [comment]
> Not so sure about the directories... I think the problem is, that you need to link at compile time and at runtime against the dylib. After reading some man pages, I think `~/lib` is _not_ one of the folders that are by default looked at for dylibs in osx (whereas your mentioned folders are part of the lookup strategy). One can adjust that with `DYLD_LIBRARY_PATH` but thats something else.

Indeed: did you try with /usr/local/lib ? Does it work? It should...

**Comment by gizmomogwai** [comment]
Mhh .. I will try now, but my machine does not even have this directory ... and in general I do not like to litter in `/` ...

**Comment by gizmomogwai** [comment]
Mhh ... I have a mixed result. It seems that the static linker picks up the dylib from /usr/local/lib, but the dynamic linker not. For that I have to point `DYLD_LIBRARY_PATH` to it.
Thanks for your help anyways .. I think now I have enough variants to select my preferred one :)
Not sure what the "official" documentation should say though.

**Comment by trikko** [comment]
I think on macOS the only pre-defined dir for libraries is /usr/local/lib on linux there are also some user-directories but not on macOS apparently...

**Comment by gizmomogwai** [comment]
It's an interesting topic. According to `man dyld` `DYLD_FALLBACK_LIBRARY_PATH` points by default to `/usr/local/lib:/usr/lib` of which the `/usr/local/lib` is much better imho than `/usr/lib`.

**Comment by trikko** [comment]
So it should works simply copying the library over `/usr/local/lib`, shouldn't it?
Maybe your config is not the default one.

**Comment by gizmomogwai** [comment]
I tested again, for me it seems, that static linking works with libwebview.dylib in /usr/local/lib, but running the program fails if I do not set DYLD_LIBRARY_PATH to /usr/local/lib.

**Comment by trikko** [comment]
I'll add your hint :)
